### PR TITLE
Lightweight callback option for HostFunc (avoiding std::function)

### PR DESCRIPTION
**Pull request by mitza-oci**

### CODE REVIEW

**Comment by swatanabe-b1** [comment]
What is the point of avoiding std::function?  If it actually makes a measurable difference, you can probably get the same improvement by changing the way the intrinsics are registered to avoid the extra function pointer.

**Comment by heifner** [comment]
I don't remember the details but it was a measurable difference.

**Comment by mitza-oci** [comment]
At least for the data set I was testing at the time. It showed up in the
critical path when profiling.

**Comment by heifner** [comment]
Overcome by events

**Pull request closed without merging**
